import React, { useState } from 'react';

interface CommunityPost {
  id: string;
  username: string;
  avatar: string;
  content: string;
  likes: number;
  comments: number;
  timestamp: string;
  userLiked: boolean;
}

const CommunitySharing: React.FC = () => {
  const [posts, setPosts] = useState<CommunityPost[]>([
    {
      id: '1',
      username: 'FitWarrior',
      avatar: '👤',
      content: 'Just hit a new PR on deadlifts! 180kg! The journey continues 💪',
      likes: 42,
      comments: 8,
      timestamp: '2 hours ago',
      userLiked: false
    },
    {
      id: '2',
      username: 'GymAddict',
      avatar: '👤',
      content: 'Completed my first marathon using the CAMTECH running plan! Never felt better 🏃‍♂️',
      likes: 28,
      comments: 5,
      timestamp: '5 hours ago',
      userLiked: true
    },
    {
      id: '3',
      username: 'HealthFirst',
      avatar: '👤',
      content: 'The nutrition calculator helped me lose 5kg in 6 weeks while maintaining muscle mass!',
      likes: 56,
      comments: 12,
      timestamp: '1 day ago',
      userLiked: false
    }
  ]);

  const [newPost, setNewPost] = useState('');

  const likePost = (postId: string) => {
    setPosts(posts.map(post => 
      post.id === postId 
        ? { ...post, likes: post.userLiked ? post.likes - 1 : post.likes + 1, userLiked: !post.userLiked }
        : post
    ));
  };

  const sharePost = () => {
    if (!newPost.trim()) return;

    const post: CommunityPost = {
      id: Date.now().toString(),
      username: 'You',
      avatar: '👤',
      content: newPost,
      likes: 0,
      comments: 0,
      timestamp: 'Just now',
      userLiked: false
    };

    setPosts([post, ...posts]);
    setNewPost('');
  };

  const shareWorkoutToCommunity = (workout: string) => {
    const post: CommunityPost = {
      id: Date.now().toString(),
      username: 'You',
      avatar: '👤',
      content: `Just completed this workout:\n"${workout.substring(0, 100)}..."\nGenerated by CAMTECH AI Coach 💪`,
      likes: 0,
      comments: 0,
      timestamp: 'Just now',
      userLiked: false
    };

    setPosts([post, ...posts]);
  };

  return (
    <div className="card community-card">
      <div className="section-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <i className="fas fa-users" style={{ color: 'var(--primary)' }}></i>
          <h2>Fitness Community</h2>
        </div>
        <span className="badge">Live</span>
      </div>

      <div className="post-creator">
        <div className="creator-header">
          <div className="user-avatar">👤</div>
          <div className="user-info">
            <div className="username">Share your progress</div>
            <div className="user-handle">@camtech_member</div>
          </div>
        </div>
        <textarea
          className="post-input"
          value={newPost}
          onChange={(e) => setNewPost(e.target.value)}
          placeholder="Share your workout achievements, ask questions, or motivate others..."
          rows={3}
        />
        <div className="post-actions">
          <div className="action-icons">
            <button className="icon-btn" title="Add photo">
              <i className="fas fa-image"></i>
            </button>
            <button className="icon-btn" title="Add workout">
              <i className="fas fa-dumbbell"></i>
            </button>
            <button className="icon-btn" title="Add location">
              <i className="fas fa-location-dot"></i>
            </button>
          </div>
          <button className="btn btn-primary" onClick={sharePost} disabled={!newPost.trim()}>
            <i className="fas fa-paper-plane"></i> Post
          </button>
        </div>
      </div>

      <div className="community-feed">
        {posts.map((post) => (
          <div key={post.id} className="community-post">
            <div className="post-header">
              <div className="post-user">
                <div className="post-avatar">{post.avatar}</div>
                <div>
                  <div className="post-username">{post.username}</div>
                  <div className="post-time">{post.timestamp}</div>
                </div>
              </div>
              <button className="post-menu">
                <i className="fas fa-ellipsis-h"></i>
              </button>
            </div>
            
            <div className="post-content">
              {post.content}
            </div>
            
            <div className="post-stats">
              <button 
                className={`stat-btn ${post.userLiked ? 'liked' : ''}`}
                onClick={() => likePost(post.id)}
              >
                <i className="fas fa-heart"></i> {post.likes}
              </button>
              <button className="stat-btn">
                <i className="fas fa-comment"></i> {post.comments}
              </button>
              <button className="stat-btn">
                <i className="fas fa-share"></i> Share
              </button>
              <button className="stat-btn">
                <i className="fas fa-bookmark"></i> Save
              </button>
            </div>
          </div>
        ))}
      </div>

      <div className="community-tips">
        <div className="tip-header">
          <i className="fas fa-lightbulb"></i>
          <span>Community Tips</span>
        </div>
        <div className="tips-grid">
          <div className="tip-card">
            <i className="fas fa-hands-clapping"></i>
            <div>Celebrate small wins</div>
          </div>
          <div className="tip-card">
            <i className="fas fa-handshake"></i>
            <div>Support others</div>
          </div>
          <div className="tip-card">
            <i className="fas fa-shield"></i>
            <div>Keep it positive</div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CommunitySharing;
